function Flag_Custom() {
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.NAME,"PLAYER");
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.LV,19);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.HP_MAX,92);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.HP,92);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM,-3);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+1,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+2,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+3,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+4,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+5,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+6,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+7,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM_WEAPON,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM_ARMOR,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ATK,99);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.DEF,99);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.SPD,2.5);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.INV,40);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.BATTLE_MENU_FIGHT_OBJ,battle_menu_fight_knife);

	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.BATTLE_ROOM_RETURN,-1);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.TRIGGER_WARP_LANDMARK,noone);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.TRIGGER_WARP_DIR,-1);

	Item_SetWeapon(-1);
	Item_SetArmor(-1);

	Item_Add(item_pie);
	Item_Add(item_steak);
	Item_Add(item_snowman_piece);
	Item_Add(item_snowman_piece);
	Item_Add(item_noodles);
	Item_Add(item_legendary_hero);
	Item_Add(item_legendary_hero);
	Item_Add(item_legendary_hero);


}
